interaction:
  - class_name: "env_tuning.interaction.new_multi_turn_fc.MultiTurnFunctionCallInteraction"
    config:
      name: "multi_turn_tool_call"
      seet:
        enabled: true
        stage: 3
        retry_probability: 0.2
        max_retry_per_turn: 1
